/**
 * 견주 마이페이지 승인 거부 시 사용되는 localStorage key를 관리합니다.
 */
export const STORAGE_KEY = {
  VISIT_MYPAGE: "VISIT-MYPAGE",
  ENROLLMENT_FORM_ID: "ENROLLMENT-FORM-ID",
  APPROVAL_DENIED: "APPROVAL-DENIED",
  DOG_ENROLLMENT_DATA: "DOG-ENROLLMENT-DATA"
};

/**
 * 견주 마이페이지 강아지 상태를 표시합니다.
 */
export const DOG_STATUS = {
  ENROLLED: "ENROLLED",
  APPROVAL_PENDING: "APPROVAL_PENDING",
  APPROVAL_CANCEL: "APPROVAL_CANCEL",
  DROP_OUT: "DROP_OUT",
  APPROVAL_DENIED: "APPROVAL_DENIED"
};
