import { ITEM_KEYS } from "./item";

/**
 * 강아지 상세 정보 > 가입신청서의 requiredItems
 * 필수입력, 선택 입력 표시
 */
export const REQUIRED_ITEMS_DOG_MAP = new Map<number, boolean>([
  [ITEM_KEYS.MEMBER_NAME, false],
  [ITEM_KEYS.MEMBER_GENDER, true],
  [ITEM_KEYS.MEMBER_ADDRESS, false],
  [ITEM_KEYS.MEMBER_PHONE, false],
  [ITEM_KEYS.EMERGENCY_NUMBER, false],
  [ITEM_KEYS.DOG_NAME, false],
  [ITEM_KEYS.DOG_GENDER, true],
  [ITEM_KEYS.DOG_SIZE, false],
  [ITEM_KEYS.DOG_BREED, false],
  [ITEM_KEYS.DOG_BIRTHDAY, false],
  [ITEM_KEYS.NEUTRALIZATION, true],
  [ITEM_KEYS.VACCINATION, true],
  [ITEM_KEYS.VACCINATION_FILE, false],
  [ITEM_KEYS.ALLERGY_DISEASE, false],
  [ITEM_KEYS.TICKET_TYPE, false],
  [ITEM_KEYS.MONTHLY_TICKET_NUMBER, true],
  [ITEM_KEYS.ROUND_TICKET_NUMBER, true],
  [ITEM_KEYS.OPEN_DAYS, true],
  [ITEM_KEYS.TICKET_INFO, true],
  [ITEM_KEYS.LIMITS_INFO, true],
  [ITEM_KEYS.ACCIDENT_INFO, true],
  [ITEM_KEYS.ABANDONMENT_INFO, true],
  [ITEM_KEYS.ABANDONMENT_INFO, true],
  [ITEM_KEYS.PICKDROP_REQUEST, true],
  [ITEM_KEYS.PICKDROP_TYPE, true],
  [ITEM_KEYS.PICKDROP_MEMO, true],
  [ITEM_KEYS.PICKDROP_INFO, true],
  [ITEM_KEYS.ABANDONMENT_INFO, true]
]);
