export const ACCESS_TOKEN_KEY = "KNOCK-DOG-AUTH-TOKEN";
export const SCHOOL_NAME_KEY = "KNOCK-DOG-SCHOOL-NAME";
export const USER_TYPE_KEY = "KNOCK-DOG-USER-TYPE";
export const SORT_NAME_KEY = "KNOCK-DOG-SORT-NAME";
